name: users
endpoint: /api/nexus/users
port: 8080
request:
  user_id: String
response:
  name: String
  age: int
  gender: String
sql: |
  select user_id,
        name,
        email,
        address
  from
        users
  where
        user_id='{{user_id}}'
db:
  driver: SnowflakeDSIIDriver
  hostname: mzgcmdm-zc86758.snowflakecomputing.com
  username: PLACEHOLDER_USERNAME
  password: PLACEHOLDER_PASSWORD
  database: nexus_db
  schema: nexus
  role: ACCOUNTADMIN
  warehouse: compute_wh
